# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            YoungEun 개발 블로그
tagline:          'youngeun'
description:      영은의 개발 블로그
url:              "https://youngniw.github.io/"
baseurl:          ""

author:
  name:           'YoungEun Wi'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/youngniw
