title: YoungEun 개발 블로그
description: Created a blog on March 30, 2021.
author: YoungEun Wi
avatar: /logo.jpg
email: 1999julie@naver.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  
skin: daylight

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.jpg
social:
  name: YoungEun Wi
  links:
    - https://github.com/youngniw
google_site_verification: 
lang: ko
